apiVersion: v1
kind: Service
metadata:
  name: document-upload-service
  namespace: dukqa-apps
  labels:
    app: document-upload-service
spec:
  type: ClusterIP
  selector:
    app: document-upload-service
  ports:
    - name: http
      port: 80
      targetPort: 8080
      protocol: TCP

