apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-service-config
  namespace: ec2-apps
data:
  NODE_ENV: "production"
  PORT: "3000"
  NEXT_PUBLIC_API_URL: "https://api.dukqa-platform.com"
  NEXT_PUBLIC_APP_NAME: "DukQa Platform"
  NEXT_PUBLIC_B2C_PORTAL: "true"
  NEXT_PUBLIC_B2B_PORTAL: "true"
  NEXT_PUBLIC_ADMIN_PORTAL: "true"