apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-service
  namespace: ec2-apps
  labels:
    app: frontend-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend-service
  template:
    metadata:
      labels:
        app: frontend-service
    spec:
      serviceAccountName: frontend-service-sa
      containers:
        - name: frontend
          image: 746387399274.dkr.ecr.eu-west-1.amazonaws.com/dukqa-platform:frontend-service-latest
          ports:
            - containerPort: 3000
              name: http
          envFrom:
            - configMapRef:
                name: frontend-service-config
                optional: false
            - secretRef:
                name: frontend-service-secret
                optional: false