apiVersion: v1
kind: Service
metadata:
  name: kra-integration-service
  namespace: dukqa-apps
spec:
  selector:
    app: kra-integration-service
  ports:
    - port: 80
      targetPort: 8080
  type: ClusterIP

