apiVersion: v1
kind: Service
metadata:
  name: customer-support-service
  namespace: dukqa-apps
  labels:
    app: customer-support-service
spec:
  type: ClusterIP
  selector:
    app: customer-support-service
  ports:
    - port: 80
      targetPort: 8080

