apiVersion: v1
kind: Service
metadata:
  name: kq-flight-cargo-service
  namespace: dukqa-apps
spec:
  type: ClusterIP
  selector:
    app: kq-flight-cargo
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP

