apiVersion: v1
kind: ConfigMap
metadata:
  name: auth-service-config
  namespace: ec2-apps
data:
  LOG_LEVEL: "info"
  DB_HOST: "<RDS_ENDPOINT>"
  DB_PORT: "5432"
  DB_NAME: "appdb"
  DB_USER: "appuser"

