apiVersion: v1
kind: Service
metadata:
  name: insurance-service
  namespace: dukqa-apps
spec:
  type: ClusterIP
  selector:
    app: insurance
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP

