apiVersion: v1
kind: ConfigMap
metadata:
  name: payments-config
  namespace: dukqa-apps
data:
  APP_ENV: "production"
  LOG_LEVEL: "info"
  PAYMENT_GATEWAY_URL: "https://api.stripe.com"
  CURRENCY: "KES"

